blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_blog.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/urls.py
from django.urls import path
from.views import *

app_name = 'my_blog'

urlpatterns = [
    path('', home, name='home'),
    path('get_article/', get_article, name='get_article'),
    path('add_post/', add_post, name='add_post'),
    path('login_admin/', login_admin, name='login_admin'),
    path('get_categories/', get_categories, name='get_categories'),
    path('add_post/', add_post, name='add_post'),
    path('update_post/<topic_id>/', update_post, name='update_post'),
]

templates/base/base.html
<html>
  <head>
    {% load static %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">BlogBound</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">

             

       
         
      
          <li class="nav-item">
            <a class="nav-link" href="{% url 'my_blog:get_categories' %}"
              >Categories</a
            >

          </li>
             
             </li>
            <li class="nav-item">
            <a class="nav-link" href=""
              >About</a
            >
          </li>
        </ul>
      </div>
    </nav>
 <link
      href="{% static 'css/bootstrap.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{% static 'css/bootstrap.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
   

    <script src="{% static 'js/bootstrap.min.js' %}"></script>


    <!-- CDN -->

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link
    href="{% static 'base.css' %}"
    rel="stylesheet"
    type="text/css"
  />


    

    <title>articles</title>
  </head>

 <body>


    <div class="container-fluid layout">
   {% block content %}

  




<div class="row">
<!--      displaying all the posts without signing in-->


<div class="col-9 card-container">

  {% for val in entries %}
<div class="card" >

<img class="card-img-top" src="{{val.get_photo_url}}" alt="Card image cap">
<div class="card-body" href="#">
<b>{{val.topic.name}}</b>
<a href="/get_article/?id={{val.id}}"><h5 class="card-title">{{ val.topic }}</h5></a>
<p class="card-text">{{ val }} </p>
<small>{{val.date_added}}</small>

</div>



</div>

{% endfor %}
</div>
<div class="col-md-3 col-lg-3">
 
    <div class="card sidebar" >

    
      <div class="card-body" href="#">
        <ul class="most_recent"> Most recent</ul>
        
        {%  for val in entries%}
        <li>{{val.topic.name}}</li>
        {% endfor %}
      </div>
      
      </div>

</div>

   </div>



   <div class="pagination">
    {% if pages.has_previous %}
    <a href="/?page={{pages.previous_page_number}}">Previous page&laquo;</a>
    {% endif %}
    {% for p in pages.page_range %}
    <a href="/?page={{p}}">{{p}}</a>
 
    {% endfor %}
    {% if pages.has_next %}
    <a href="/?page={{pages.next_page_number}}"> Next page &raquo;</a>
    {% endif %}
  </div>
{% endblock content %}

</div>
 </body>

</html>